### ISSUE TITLE
0.7 touchscreen issues

### ISSUE THREAD

**Issue by camplusplus** [fayaaz/mixxx-pi-gen#48]
Seems like 0.7 ver has a new hid library and touch on small 800*400 elecrow screen is affected: cannot click Fullscreen library button.

**Comment by camplusplus** [comment]
Also controller mapping for selection of track in library not working with loaded mapping

**Comment by fayaaz** [comment]
> Also controller mapping for selection of track in library not working with loaded mapping

I expect this is to do with subtle changes to the controls in Mixxx 2.4 - what controller is this? It will need to be reported to Mixxx.

> Seems like 0.7 ver has a new hid library and touch on small 800*400 elecrow screen is affected: cannot click Fullscreen library button.

Is this installed as part of Debian 11 or because of the build (I know there's been some updates to hid within Mixxx but don't expect this to affect touchscreens)? I wonder if the Raspberry Pi OS image also has this problem.

**Comment by camplusplus** [comment]
Controller is Reloop Beatmix 2. 
I suspect that it's debian issue as touch is a little bit off.

Thanks for your help and time!

**Comment by camplusplus** [comment]
It's hardware problem with my screen. Touch is unreliable also stops on older version. 
Thanks for the great distro!
