### ISSUE TITLE
Rekordbox Flashdrive readability

### ISSUE THREAD

**Issue by rschlek** [fayaaz/mixxx-pi-gen#52]
There is no functionality for mounting a flashdrive, and once mounted a rekordbox formatted flashdrive is unrecognizable by mix.

**Comment by fayaaz** [comment]
That is unexpected.

https://github.com/fayaaz/mixxx-pi-gen/blob/47b54d8dd44f6363078e7df79d7e68fbf555493f/stage3/02-desktop/files/i3.conf#L176
This line should start devmon and automatically mount USBs. Others have said this is working.

Since Mixxx 2.3 I have had others use rekordbox USBs with my setup  on my laptop and those worked well. I will try and test it on the rpi image. Could you give me the steps you used to format and create your rekordbox formatted flashdrives? What filesystem is it for example?
